language: scala
script:
  # the concurrentRestrictions should prevent spurious test failures, see https://github.com/spray/spray/pull/233
  - sbt ++$TRAVIS_SCALA_VERSION 'set concurrentRestrictions in Global += Tags.limit(Tags.Test, 1)' clean update compile test
scala:
  - 2.11.0-SNAPSHOT
jdk:
  - openjdk6
  - openjdk7
notifications:
  email:
    - adriaan.moors@typesafe.com
